services:
  roomsdesigner.api:
    image: ${DOCKER_REGISTRY-}roomsdesignerapi
    build:
      context: .
      dockerfile: RoomsDesigner/Dockerfile      
    container_name: roomsdesigner-service
    environment:
      ConnectionStrings:Postgres: "Host=roomsdesigner_db;Port=5432;Database=room;UserId=postgres;Password=admin24"      
      ApiGateWaySettings:ValidApiKeys: ${GATEWAY_KEY_HABIT} 
      RmqSettings:Host: "habit-rabbit"
      RmqSettings:VHost: "/"
      RmqSettings:Login: "guest"
      RmqSettings:Password: "guest"
    depends_on:
      - roomsdesigner_db
    networks:
      - devnet

  roomsdesigner_db:
    image: postgres
    container_name: roomsdesigner_db
    restart: always
    environment:    
      POSTGRES_DB: room
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin24
    ports:
      - "5543:5432"
    volumes:
      - 'roomsdesigner_data:/var/lib/postgresql/data'
    networks:
      - devnet
  
  # habit-rabbit:
  #   image: rabbitmq:3-management
  #   container_name: 'habit-rabbit'
  #   restart: always
  #   hostname: rabbitmqhost    
  #   environment:
  #     RABBITMQ_DEFAULT_USER: guest
  #     RABBITMQ_DEFAULT_PASS: guest
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
volumes:
  roomsdesigner_data:
  rabbitmq_data:

networks:
  devnet:
    name: devnet
    driver: bridge
