services:
  roomsdesigner.api:
    image: ${DOCKER_REGISTRY-}roomsdesignerapi
    build:
      context: .
      dockerfile: RoomsDesigner/Dockerfile      
    container_name: roomsdesigner-service
    environment:
      "ASPNETCORE_URLS": "http://+:5100"
      ConnectionStrings:Postgres: "Host=roomsdesigner_db;Port=5432;Database=room;UserId=postgres;Password=admin24"
      RmqSettings:Host: "habit-rabbit"
      RmqSettings:VHost: "/"
      RmqSettings:Login: "guest"
      RmqSettings:Password: "guest"
    depends_on:
      - roomsdesigner_db
    ports:
      - "5200:5100"

  roomsdesigner_db:
    image: postgres
    container_name: roomsdesigner_db
    restart: always
    environment:    
      POSTGRES_DB: room
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin24
    ports:
      - "5543:5432"
    volumes:
      - 'roomsdesigner_data:/var/lib/postgresql/data'

  postgres:
    image: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    container_name: keycloak_web
    image: quay.io/keycloak/keycloak:24.0.4
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
      PROXY_ADDRESS_FORWARDING: true
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

  
  # habit-rabbit:
  #   image: rabbitmq:3-management
  #   container_name: 'habit-rabbit'
  #   restart: always
  #   hostname: rabbitmqhost    
  #   environment:
  #     RABBITMQ_DEFAULT_USER: guest
  #     RABBITMQ_DEFAULT_PASS: guest
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"

volumes:
  roomsdesigner_data:
  rabbitmq_data:
  pg-data:
